name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa automaticamente todo dia à meia-noite UTC
  workflow_dispatch:  # Permite rodar manualmente

permissions:
  contents: write  # Dá permissão para escrever no repositório

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from Commit History
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
